apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind-deployment
  labels:
    app: kind-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kind-deployment
  template:
    metadata:
      labels:
        app: kind-deployment
    spec:
      containers:
      - name: helloworldv2
        image: ledu32/helloworld
        ports:
        - containerPort: 5000
