apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
{{ toYaml .Values.resources | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}