apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: helloworldv2
        image: ledu32/helloworldv2:latest
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 10
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 0.5
          requests:
            cpu: 0.25
