apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: {{ .Values.hpa.scaleTargetRef.apiVersion }}
    kind: {{ .Values.hpa.scaleTargetRef.kind }}
    name: {{ .Values.hpa.scaleTargetRef.name }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}