apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.ingress.hosts }}  
    http:
      paths:
      - path: /nginx
        pathType: {{ .Values.ingress.pathType }}
        backend: 
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.port }}