apiVersion: v1
kind: Service
metadata:
  name: service
  annotations:
    se7entyse7en.prometheus/scrape: "true"
    se7entyse7en.prometheus/path: "/metrics"
    se7entyse7en.prometheus/port: "80"
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 5000