name: Docker image tester

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
 # release:
  #  types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Build Docker image
      run: docker build -f Dockerfile -t ledu32/helloworld .

    - name: Load image to Kind cluster
      run: kind load docker-image ledu32/helloworld --name chart-testing

    - name: Kustomize Github Action
      uses: karancode/kustomize-github-action@v1.3.2

    - name: Test Kustomization
      run: kustomize build . | k apply kubectl apply -f kind-deployment.yaml

 #   - name: Apply deployment to Kind clister
  #    run: kubectl apply -f kind-deployment.yaml

    - name: Wait for pod to be Ready
      run: kubectl wait --for=condition=Ready pod -l app=kind-deployment