name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Build Helm Chart
      run: |
       helm package .
       echo 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 | helm registry login ghcr.io -u Ledu0032 --password-stdin
       helm push helloworldv2-0.1.0.tgz oci://ghcr.io/ledu0032/helloworld

