name: Docker image tester

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
 # release:
  #  types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
#
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Install Kind Cluster
      run: |
        kubectl get nodes
        docker pull ghcr.io/ledu0032/helloworld:main
        kind load docker-image ghcr.io/ledu0032/helloworld:main --name chart-testing
        kubectl apply -f ./deployment.yaml -f ./service.yaml -f ./ingress -f ./kind-cluster