name: Helm Chars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build and push Helm Charts
      run: |
        helm package .
    
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.3.0
      with:
        name: my-chart
        repository: appany
        tag: 0.1.0
        path: charts/my-chart # Default charts/{name}
        registry: ghcr.io
        registry_username: ${{ secrets.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}






