name: Helm Chars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  stale:
   
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Package helm charts
      run: helm package .

    - uses: actions/checkout@v3
    - name: Push helm chart
      run: helm push helloworldv2-0.1.0.tgz oci://ghcr.io/ledu0032/helloworld
