name: Helm Chars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:

  build:
   
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package helm charts
      run: |
        helm package .
        helm push helloworldv2-0.1.0.tgz oci://ghcr.io/ledu0032/helm-chats

    - name: Testing Helm Chars
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

