name: Helm Chars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Package helm charts
      run: helm package .

    - uses: actions/checkout@v3
    - name: Push helm chart
      run: |
        echo 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 | helm registry login ghcr.io -u Ledu0032 --password-stdin
        helm push helloworldv2-0.1.0.tgz oci://ghcr.io/ledu0032/helm-chats
