name: Helm Chars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    type: published

permissions:
  contents: write
  packages: write

jobs:

  build:
   
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1

    - name: Lint Charts
      run: |
        ct lint --all --validate-maintainers=false --chart-dirs chart
      
    - name: Install Linted charts
      run: |
        ct install --all --chart-dirs chart

    - name: Package helm charts
      run: |
        cd chart
        helm package .
        helm push helloworldv2-*.tgz oci://ghcr.io/ledu0032/helm-chats