name: Helm Chars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Package helm charts
      run: helm package .

    - name: Helm Push
      uses: bsord/helm-push@v4.1.0






